<?php

// if( function_exists('acf_add_local_field_group') ):
//
// acf_add_local_field_group(array(
//   'key' => 'group_5d04921e5c6a1',
//   'title' => 'Accomplishments',
//   'fields' => array(
//     array(
//       'key' => 'field_5d049252cdd66',
//       'label' => 'Title',
//       'name' => 'accomplishments_block_01_title',
//       'type' => 'text',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => 'accomplishments_block_01_title',
//       'prepend' => '',
//       'append' => '',
//       'maxlength' => '',
//     ),
//     array(
//       'key' => 'field_5d0492b9cdd67',
//       'label' => 'Description',
//       'name' => 'accomplishments_block_01_description',
//       'type' => 'textarea',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'maxlength' => '',
//       'rows' => 4,
//       'new_lines' => '',
//     ),
//     array(
//       'key' => 'field_5d049a92bc0c7',
//       'label' => 'Title',
//       'name' => 'accomplishments_block_02_title',
//       'type' => 'text',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'prepend' => '',
//       'append' => '',
//       'maxlength' => '',
//     ),
//     array(
//       'key' => 'field_5d049ab3bc0c8',
//       'label' => 'Description',
//       'name' => 'accomplishments_block_02_description',
//       'type' => 'textarea',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'maxlength' => '',
//       'rows' => 4,
//       'new_lines' => '',
//     ),
//     array(
//       'key' => 'field_5d049add52807',
//       'label' => 'Title',
//       'name' => 'accomplishments_block_03_title',
//       'type' => 'text',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'prepend' => '',
//       'append' => '',
//       'maxlength' => '',
//     ),
//     array(
//       'key' => 'field_5d049ae852808',
//       'label' => 'Description',
//       'name' => 'accomplishments_block_03_description',
//       'type' => 'textarea',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'maxlength' => '',
//       'rows' => 4,
//       'new_lines' => '',
//     ),
//     array(
//       'key' => 'field_5d049b00edbfc',
//       'label' => 'Title',
//       'name' => 'accomplishments_block_04_title',
//       'type' => 'text',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'prepend' => '',
//       'append' => '',
//       'maxlength' => '',
//     ),
//     array(
//       'key' => 'field_5d049b0eedbfd',
//       'label' => 'Description',
//       'name' => 'accomplishments_block_04_description',
//       'type' => 'textarea',
//       'instructions' => '',
//       'required' => 0,
//       'conditional_logic' => 0,
//       'wrapper' => array(
//         'width' => '',
//         'class' => '',
//         'id' => '',
//       ),
//       'default_value' => '',
//       'placeholder' => '',
//       'maxlength' => '',
//       'rows' => 4,
//       'new_lines' => '',
//     ),
//   ),
//   'location' => array(
//     array(
//       array(
//         'param' => 'page',
//         'operator' => '==',
//         'value' => '11',
//       ),
//     ),
//   ),
//   'menu_order' => 0,
//   'position' => 'normal',
//   'style' => 'default',
//   'label_placement' => 'top',
//   'instruction_placement' => 'label',
//   'hide_on_screen' => '',
//   'active' => true,
//   'description' => '',
// ));
//
// endif;
